name: Tests

on:
  push:
    branches: [ main, develop ]
    tags-ignore:
      - 'v*.*.*'  # Don't run tests on release tags
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      
      - name: Download dependencies
        run: go mod download
      
      - name: Run tests
        run: go test -v -cover ./...
      
      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --out-format=colored-line-number
      
      - name: Build
        run: go build -v .

  build:
    runs-on: ubuntu-latest
    needs: test
    
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      
      - name: Build for ${{ matrix.os }}-${{ matrix.arch }}
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o defenra-agent-${{ matrix.os }}-${{ matrix.arch }} .
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: defenra-agent-${{ matrix.os }}-${{ matrix.arch }}
          path: defenra-agent-${{ matrix.os }}-${{ matrix.arch }}
